### ISSUE TITLE
Broken “/v1/completion/typed”

### ISSUE THREAD

**Issue by nsbradford** [thiggle/api#1]
Appears to be failing in both playground and API.

Playground: use the Thiggle `/typed` JSON endpoint using the example from the docs, but am getting "Error (400) Schema must be an exported TypeScript type". Other variations I've tried (e.g. using a `type` instead of `interface`) give me "generating..." indefinitely.

![Screenshot 2023-09-06 at 11 24 21 AM (2)](https://github.com/thiggle/api/assets/6633811/33982f91-ea10-4403-a090-2005703476a1)

Using type:
![image](https://github.com/thiggle/api/assets/6633811/293a1306-77e8-431c-80f0-4dca7b9d840b)

The pip package hasn't been updated to included the endpoint which was [added](https://github.com/thiggle/api/commit/ff1b16f2cdec4cfa8dfec1fd88b5691f2e94a8ef) a couple days ago, but using `curl` using the example from the [docs](https://docs.thiggle.com/api-docs/typed) fails with payment balance issue even though I've subscribed and added a balance (here
```
$ curl -X POST "https://api.thiggle.com/v1/completion" \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $THIGGLE_API_KEY" \
     -d '{
         "user_id": "a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890",
         "prompt": "Write a sentence",
         "max_tokens": 20,
         "temperature": 0.8,
         "top_p": 0.9,
         "stop": ["."],
         "presence_penalty": 0.6,
         "frequency_penalty": 0.5,
         "schema": "export type BasicSentence = {\n  text: string;\n}",
         "type_name": "BasicSentence"
     }'

{"code":402,"error":"Payment required: Insufficient credit balance"}%                                                                 
```

**Comment by r2d4** [comment]
Debugging a few issues:

* TODO: still need to publish the updated pip package 0.0.6
* TODO: The endpoint in your example is the /v1/completion endpoint, which is the Model API Gateway https://docs.thiggle.com/api-docs/completion, not the typed completion endpoint. Will make this clearer in the docs and on the site
* TODO: Better error handling. Especially for TypeScript definition bugs. It's hard (impossible) to know how to fix something right now if it's broken (e.g., interface instead of type, missing syntax, etc.)

Some wrong documentation on my part:
* For TypeScript definitions, they should be types, not interfaces. Fixed this in the docs in https://github.com/thiggle/api/commit/6389f1f8441a1cb5bba7da73db31ccd52319993f
* For stop tokens, adding "." prevented the model from completing the correct JSON response (it would stop at the end of the sentence and not fix the closing bracket).
* User ID is not needed for the endpoint (will automatically be added with your authentication). Already fixed this in the same commit. 

Here's an API call using cURL that should work
```bash
curl -X POST "https://api.thiggle.com/v1/completion/typed" \    [9:28:29]
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer $THIGGLE_API_KEY" \
     -d '{
         "prompt": "Write a sentence",
         "schema": "export type BasicSentence = { text: string;}",
         "type_name": "BasicSentence"
     }'
```

**Comment by nsbradford** [comment]
ah, my mistake in the URL - working fine for me now, thanks! 

I notice /completion/typed does not take a `model` parameter (right now I get the empty string in my responses) - is this customizable? i didn't see any info in the docs about what the default model is.

**Comment by r2d4** [comment]
@nsbradford Not customizable right now. The structured APIs (regex, completion, and now typed) aren't customizable w.r.t. models. Might expose this in the future, but first working on optimizing the APIs and infrastructure before opening it up to more models or even custom models.

**Comment by nsbradford** [comment]
makes sense, thanks for helping! 🙂
